### ISSUE TITLE
[MAPPING] when filtering by mapper, sometimes all synapses do not reappear after filtering is cleared.

### ISSUE THREAD

**Issue by poietic** [metamaps/metamaps_gen002#391]
Nov 21 2015 remaining tasks are:

- [x] Update filter box properly on new synapse creation
- [x] Fix forking code to take into account newly created synapses (this probably means updating something else in javascript).

**Comment by poietic** [comment]
would be really great to have this one fixed...i often run into it when showing people the filtering functionality.

**Comment by Tadasu85** [comment]
The problem here is being caused by the _filterBox.html.erb that is where the code resides that controls this, now i believe this issue is being caused by null synapses and how the code uses .desc to select synapses, so if the synapse.desc is null it gets dropped off the list no matter what. I believe Connor did give me a resolution to this issue, but I am not recalling what it was. I am going to take a crack at it and see if I can do anything with it. However no guarantee.

**Comment by Bortseb** [comment]
isn't _filterBox.html.erb just for populating the filer interface elements with all the necessary icons and clickable divs/li ?

maybe the code for the actual filtering is somewhere around here:
https://github.com/metamaps/metamaps_gen002/blob/253ceb4b48307b7afb5ebda4511db1921eb9dc5a/app/assets/javascripts/src/Metamaps.js#L3520

Though, I can't seem to make sense of this code right now

**Comment by Tadasu85** [comment]
I dont believe that is where the issue is, I think it really is just a question of within the erb file having a check to see if the synapse is null and if it is then to fill it with I dont know NULL SYNAPSE or something along those lines or UNNAMED.

**Comment by poietic** [comment]
does that mean it'll show up with that text, "NULL SYNAPSE" or "UNNAMED" on the interface?

**Comment by Tadasu85** [comment]
Potentially, i guess that is still undesirable isnt it?

**Comment by poietic** [comment]
yep that will not work at all. some people love mapping and not using the synapse descriptions at all, and that would create a lot of visual noise on the map.

**Comment by Tadasu85** [comment]
No no that description would actually only show up in the filterbox not on the map itself.

**Comment by poietic** [comment]
ah! yes then that's fine. "Unnamed" would be good then.

**Comment by Bortseb** [comment]
So, it seems not all blank synapses are created equal. Some have a desc="" and some have a desc of NULL

**Comment by Tadasu85** [comment]
I think this statement needs to go into the metamaps book of quotes. Just
awesome.

On Thu, Mar 5, 2015 at 12:33 AM, Robert Best <notifications@github.com>
wrote:

> So, it seems not all blank synapses are created equal. Some have a desc=""
> and some have a desc of NULL
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/metamaps/metamaps_gen002/issues/391#issuecomment-77309587>
> .
>



-- 
One can accomplish many things,
but many can accomplish more.

**Comment by Tadasu85** [comment]
Connor and I have made some further progress here but I have found something new as well. Here are all the notes from out most recent session connor [9:42 PM] 
I believe that passing `model.get(propertyToCheck)` instead of `false` on 3266, 3272, and 3280 should actually do the trick

connor [9:44 PM]
but then also removing the check for `prop` from 3267, 3273, and 3281 should also happen, because what I'm basically saying is that now we should let model.get('desc') through even if the value is `undefined`

connor [9:44 PM]
@raymon ^^

connor [9:45 PM]
so the origin of the issue actually appears to be in `updateFilters`

raymon [9:57 PM] 
alright let me see if I can set that up then

raymon [10:04 PM] 
awesome that does seem to fix it except for one really wierd case with the first synapse, i need to some further digging on it.

raymon [10:14 PM] 
ok so the very first synpase that is created on a map if it is created with no description gets created as an actually null string however any other after that are created as a blank string which is what is causing the last of the issues here. so what I need to do is make it so that when that first synapse is created it is actually created like this : "" rather then just null

raymon [10:18 PM]
and for that I should be able to set it in synapse.rb correct?  under models so that when that class is created it is created with a string for the desc?

raymon [11:14 PM] 
alright well I seem to have been able to resolve the null synapse thing mind you I really dont know what other kind of issues this may cause in the code... but with your work connor and mine this wierd bug seems to be resolved.

raymon [11:15 PM]
however I was just thinking we should really do a migration that appends the db so that all synapse.desc are set to string and there are none left that are just null as well.

raymon [11:25 PM] 
Yea alright nvm I need to do some further work on this now it has created a new case from the filtering

**Comment by devvmh** [comment]
I agree with updating all null synapse descriptions to "", yeah, that is a good plan.

I think the origin of the null string is probably metamaps_gen002/app/views/maps/_newsynapse.html.erb. There's no value on the descrption text field. You can change this by adding val="" in that file and I'm guessing it'll do the trick

**Comment by Connoropolous** [comment]
yep, +1 to Devin's suggestion

**Comment by Tadasu85** [comment]
Interesting well I guess I may have understood this a little differently,
which I will amend obviously I modified it with synapse.erb and simply
defined desc inside there as a blank string "" and that seems to have
resolved it but created a new issue, I will go back remove that and do it
the way you have suggested Devin thanks man :) and thank you Connor for
verification.

On Mon, Mar 16, 2015 at 9:12 AM, Connor Turland <notifications@github.com>
wrote:

> yep, +1 to Devin's suggestion
>
> On Mon, Mar 16, 2015 at 8:22 AM, Devin Howard <notifications@github.com>
> wrote:
>
> > I agree with updating all null synapse descriptions to "", yeah, that is
> a
> > good plan.
> >
> > I think the origin of the null string is probably
> > metamaps_gen002/app/views/maps/_newsynapse.html.erb. There's no value on
> > the descrption text field. You can change this by adding val="" in that
> > file and I'm guessing it'll do the trick
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/metamaps/metamaps_gen002/issues/391#issuecomment-81616576
> >
> > .
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/metamaps/metamaps_gen002/issues/391#issuecomment-81654601>
> .
>



-- 
One can accomplish many things,
but many can accomplish more.

**Comment by devvmh** [comment]
Is synapse.erb a model thing? I don't know of this file, but it may be
smart to do it in both spots. I'm imagining this is like always sending
blank strings by default (via the _newsynapse.html.erb file), but if a bug
in the future sends null then it'll switch it to "" automatically because
of the synapse.erb thing

**Comment by Tadasu85** [comment]
Alright yeppers perfect, so now ive changed it in both spots. I think I
need to push this up actually into my branch maybe and see if anyone else
can see what the problem is here, when I click on that blank synapse in the
filter box now it is disabling everying, all mappers and all topics. I will
push my current state up to my branch later on today.

On Mon, Mar 16, 2015 at 3:39 PM, Devin Howard <notifications@github.com>
wrote:

> Is synapse.erb a model thing? I don't know of this file, but it may be
> smart to do it in both spots. I'm imagining this is like always sending
> blank strings by default (via the _newsynapse.html.erb file), but if a bug
> in the future sends null then it'll switch it to "" automatically because
> of the synapse.erb thing
> On Mar 16, 2015 3:05 PM, "Raymon Johnstone" <notifications@github.com>
> wrote:
>
> > Interesting well I guess I may have understood this a little differently,
> > which I will amend obviously I modified it with synapse.erb and simply
> > defined desc inside there as a blank string "" and that seems to have
> > resolved it but created a new issue, I will go back remove that and do it
> > the way you have suggested Devin thanks man :) and thank you Connor for
> > verification.
> >
> > On Mon, Mar 16, 2015 at 9:12 AM, Connor Turland <
> notifications@github.com>
> > wrote:
> >
> > > yep, +1 to Devin's suggestion
> > >
> > > On Mon, Mar 16, 2015 at 8:22 AM, Devin Howard <
> notifications@github.com>
> > > wrote:
> > >
> > > > I agree with updating all null synapse descriptions to "", yeah, that
> > is
> > > a
> > > > good plan.
> > > >
> > > > I think the origin of the null string is probably
> > > > metamaps_gen002/app/views/maps/_newsynapse.html.erb. There's no value
> > on
> > > > the descrption text field. You can change this by adding val="" in
> that
> > > > file and I'm guessing it'll do the trick
> > > >
> > > > --
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > >
> >
> https://github.com/metamaps/metamaps_gen002/issues/391#issuecomment-81616576
> > > >
> > > > .
> > >
> > > >
> > >
> > > --
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/metamaps/metamaps_gen002/issues/391#issuecomment-81654601
> > >
> > > .
> > >
> >
> >
> >
> > --
> > One can accomplish many things,
> > but many can accomplish more.
> >
> > --
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/metamaps/metamaps_gen002/issues/391#issuecomment-81875607
> >
> > .
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/metamaps/metamaps_gen002/issues/391#issuecomment-81892184>
> .
>



-- 
One can accomplish many things,
but many can accomplish more.

**Comment by devvmh** [comment]
Update: I've done a bit of work on this. This same bug also leads to synapses sometimes not appearing in a fork of the map.

**Comment by poietic** [comment]
great i'm glad there was some prior sensemaking around this issue to build on.

**Comment by devvmh** [comment]
I just confirmed that a new synapse created on my local dev instance on the latest develop branch (with rails 4 changes) was correctly saved to the DB. It shows up in Backbone as desc: "", it shows up in the rails console as desc: "", and it shows up in the filter box as a little lightning bolt with nothing underneath. 

Remaining problems:
- [ ] When I first create a blank synapse, the new filter option doesn't appear in thefilter box (this may be more widespread)
- [ ] I need to check whether desc: " " will be confused with desc: "" in the filter box

**Comment by devvmh** [comment]
I opened a map with two synapses with descriptions and one synapse with desc: "". Filtering worked correctly. Then I created two new synapses, one with desc: " " and one with desc: "". Opening the filter box, the options were unchanged. I clicked on the blank synapse filter, and the three synapses with apparently blank descriptions disappeared. Clicking it again only showed the one synapse with desc: " ", which is pretty bad!

The game is afoot

**Comment by devvmh** [comment]
Reloading the map yielded two different (apparently) blank-titled filter options in the filter box. The first had source <li data-id> and the second had source <li data-id=" ">. These correctly filtered synapses as they should.

It looks like the only remaining task is to properly update the filter box on new synapse creation, perhaps by rebuilding it entirely once Metamaps.Synapses is populated with the up to date values.

**Comment by Connoropolous** [comment]
@devvmh is this the issue to close?

**Comment by devvmh** [comment]
Yeah, although they're pretty tricky bugs so I think we should wait until
the big test and let ishan have the final say  that it's fixed. I wouldn't
want to jump the gun since this is such a tricky one

**Comment by devvmh** [comment]
fix is pushed to master - reopen if it's not fixed.
